<?php require_once './templates/header.phtml' ?>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>id</th>
            <th>producto</th>
            <th>id_categoria</th>        
        </tr>
    </thead>


    <?php foreach($pedidos as $pedido): ?>
        
 
        
        <tbody>
            <tr>
                <td><?= $pedido->id_producto ?></td>                    
                <td><?= $pedido->producto ?></td> 
                <td><?= $pedido->categoria ?></td>                 
            </tr>
        </tbody>
    <?php endforeach ?>

</table>



<?php require_once './templates/footer.phtml' ?>