<?php require_once './templates/header.phtml' ?>

<h1> LISTA DE PEDIDOS</h1>
<form method="post" action="addPedido">
    <label for="">Ingrese el producto que desea</label>
    <select name="producto" id="producto">
        <?php foreach ($productos as $producto){ ?>
            <option value="<?= $producto->nombre_producto ?>"><?= $producto->nombre_producto ?></option>
        <?php } ?>
    </select>   
    <select name="categoria" id="categoria">
        <?php foreach($categorias as $categoria){ ?>
            
            <option value="<?= $categoria->id_categoria ?>"><?= $categoria->nombre_categoria ?></option>

        <?php } ?>
    </select>   

    <button type="submit">COMPRAR</button>
    
</form>

<?php 
?>


<form method="post" action="filtro">
    <label for="">FILTRAR POR CATEGORIA</label>
    <select name="filtro" id="filtro">
        <?php foreach($categorias as $categoria){ ?>
            
            <option value="<?= $categoria->id_categoria ?>"><?= $categoria->nombre_categoria ?></option>

        <?php } ?>
    </select>   
    <button type="submit">Filtrar</button>
</form>


<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Id del pedido</th>
            <th>Id del Producto</th>
            <th>Producto</th>
            <th>Categoria</th>
            <th>Detalle Producto</th>           
        </tr>
    </thead>


    <?php foreach($pedidos as $pedido): ?>
        
 
        
        <tbody>
            <tr>
                <td><?= $pedido->id_pedido ?></td>
                <td><?= $pedido->id_producto ?></td>                    
                <td><?= $pedido->producto ?></td> 
                <td><?= $pedido->nombre_categoria ?></td>
                <td><a href="detailProduct/<?= $pedido->id_producto?>" >Detalle</a></td>   
                <td><a href="deletePedido/<?= $pedido->id_producto ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a></td>
            </tr>
        </tbody>
    <?php endforeach ?>
    
</table>
<form method="post" action="editPedido">
    <label for="">Ingrese el ID del pedido que desea editar</label>
    <input type="text" id="id_pedido" name="id_pedido">
    <label for="">Ingrese El ID del producto al que desea cambiar</label>
    <input type="text" name="id_producto" id="id_producto">
    <label for="">Ingrese el producto que desea</label>
    <input type="text" name="producto" id="producto">
    <label for="">Ingrese la categoria que desea</label>
    <input type="text" name="categoria" id="categoria">
    <button type="submit">Editar</button>
    
</form>
