<?php require_once './templates/header.phtml' ?>


<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>id producto</th>
            <th>Nombre producto</th>
            <th>Detalle producto</th>    
        </tr>
    </thead>
    
    
    <?php foreach($productos as $producto): ?>
        
        
        
        <tbody>
            <tr>
                <td><?= $producto->id_productos ?></td>                    
                <td><?= $producto->nombre_producto ?></td> 
                <td><a href="detailProduct/<?= $producto->id_productos?>" ><?= $producto->nombre_producto ?></a></td>
            </tr>
        </tbody>
        <?php endforeach ?>
        
    </table>
    
<?php require_once './templates/footer.phtml' ?>